replicaCount: 1

image:
  repository: shaniulshanto80/my-express22
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


service:
  type: NodePort
  port: 3000

serviceAccount:
      create: true

imagePullSecrets: regcred
replicaCount: 1